import type { AwsRule } from '../types';

export const awsRules: AwsRule[] = [
  {
    sourceType: 'webClient',
    targetType: 'apiGateway',
    valid: true,
    severity: 'info',
    message: 'The React browser client can call API Gateway routes for presigned URLs and metadata submission.',
    cdkHint: 'Configure API Gateway CORS and call fetch() from the frontend.',
  },
  {
    sourceType: 'webClient',
    targetType: 's3',
    valid: true,
    severity: 'warning',
    message: 'Browser direct upload to S3 is valid only through a presigned URL or equivalent scoped upload policy.',
    cdkHint: 'Use API Gateway -> Lambda to mint a presigned PUT URL; then browser PUTs directly to S3.',
    requiredPermission: 'S3 CORS must allow PUT from the frontend origin.',
  },
  {
    sourceType: 'apiGateway',
    targetType: 'lambda',
    valid: true,
    severity: 'info',
    message: 'API Gateway can invoke Lambda through a Lambda integration.',
    cdkHint: 'new apigateway.LambdaIntegration(lambdaFn)',
    requiredPermission: 'API Gateway invoke permission is added by the integration.',
  },
  {
    sourceType: 'lambda',
    targetType: 's3',
    valid: true,
    severity: 'info',
    message: 'Lambda can create presigned URLs or read/write objects in S3 when the bucket grants access.',
    cdkHint: 'bucket.grantReadWrite(lambdaFn) or bucket.grantPut(lambdaFn) for presigned upload creation',
    requiredPermission: 'bucket.grantReadWrite(lambdaFn)',
  },
  {
    sourceType: 'lambda',
    targetType: 'dynamodb',
    valid: true,
    severity: 'info',
    message: 'Lambda can access DynamoDB when the table grants data-plane permissions.',
    cdkHint: 'table.grantReadWriteData(lambdaFn)',
    requiredPermission: 'table.grantReadWriteData(lambdaFn)',
  },
  {
    sourceType: 'lambda',
    targetType: 'ec2',
    valid: true,
    severity: 'info',
    message: 'Lambda can launch EC2 instances when its execution role has EC2 launch and PassRole permissions.',
    cdkHint: 'lambdaFn.addToRolePolicy(new iam.PolicyStatement({ actions: ["ec2:RunInstances", "iam:PassRole"], resources: ["*"] }))',
    requiredPermission: 'ec2:RunInstances and iam:PassRole',
  },
  {
    sourceType: 'lambda',
    targetType: 'sqs',
    valid: true,
    severity: 'info',
    message: 'Lambda can send messages to SQS with queue send permissions.',
    cdkHint: 'queue.grantSendMessages(lambdaFn)',
    requiredPermission: 'queue.grantSendMessages(lambdaFn)',
  },
  {
    sourceType: 'sqs',
    targetType: 'lambda',
    valid: true,
    severity: 'info',
    message: 'SQS can trigger Lambda using an event source mapping.',
    cdkHint: 'lambdaFn.addEventSource(new SqsEventSource(queue))',
  },
  {
    sourceType: 's3',
    targetType: 'lambda',
    valid: true,
    severity: 'info',
    message: 'S3 can trigger Lambda using bucket notifications.',
    cdkHint: 'bucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.LambdaDestination(lambdaFn))',
  },
  {
    sourceType: 'dynamodb',
    targetType: 'lambda',
    valid: true,
    severity: 'info',
    message: 'DynamoDB Streams can trigger Lambda when streams are enabled on the table.',
    cdkHint: 'lambdaFn.addEventSource(new lambdaEventSources.DynamoEventSource(table, { startingPosition: lambda.StartingPosition.LATEST }))',
    requiredPermission: 'DynamoDB stream enabled with NEW_IMAGE or NEW_AND_OLD_IMAGES.',
  },
  {
    sourceType: 'dynamodb',
    targetType: 'apiGateway',
    valid: false,
    severity: 'error',
    message: 'DynamoDB cannot directly trigger API Gateway. Use DynamoDB Streams to Lambda, then call an API integration if needed.',
    cdkHint: 'Suggested path: DynamoDB Streams -> Lambda -> API Gateway',
  },
  {
    sourceType: 'ec2',
    targetType: 'dynamodb',
    valid: true,
    severity: 'warning',
    message: 'EC2 can read and update DynamoDB through its instance role.',
    cdkHint: 'table.grantReadWriteData(instanceRole)',
    requiredPermission: 'Attach an IAM role or instance profile to EC2.',
  },
  {
    sourceType: 'ec2',
    targetType: 's3',
    valid: true,
    severity: 'warning',
    message: 'EC2 to S3 requires an IAM role attached to the instance and an S3 grant.',
    cdkHint: 'bucket.grantReadWrite(instance.role)',
    requiredPermission: 'Attach an IAM role to EC2 and grant bucket access.',
  },
  {
    sourceType: 'iamRole',
    targetType: 'ec2',
    valid: true,
    severity: 'info',
    message: 'An EC2 instance profile can attach this role to the VM.',
    cdkHint: 'new iam.InstanceProfile(this, "Profile", { role })',
  },
  {
    sourceType: 'iamRole',
    targetType: 'lambda',
    valid: true,
    severity: 'info',
    message: 'Lambda can receive this role/profile name as configuration when it needs to pass the EC2 instance profile during RunInstances.',
    cdkHint: 'PROFILE_NAME: instanceProfile.instanceProfileName',
  },
  {
    sourceType: 'lambda',
    targetType: 'iamRole',
    valid: true,
    severity: 'info',
    message: 'Lambda can use this role/profile name as runtime configuration for EC2 launch flows.',
    cdkHint: 'PROFILE_NAME: instanceProfile.instanceProfileName',
  },
  {
    sourceType: 'iamRole',
    targetType: 's3',
    valid: true,
    severity: 'info',
    message: 'This role can be granted S3 access. If the role is attached to EC2, the VM receives this bucket permission.',
    cdkHint: 'bucket.grantReadWrite(role)',
    requiredPermission: 'Attach the role to EC2 with an instance profile.',
  },
  {
    sourceType: 'iamRole',
    targetType: 'dynamodb',
    valid: true,
    severity: 'info',
    message: 'This role can be granted DynamoDB data access. If the role is attached to EC2, the VM receives this table permission.',
    cdkHint: 'table.grantReadWriteData(role)',
    requiredPermission: 'Attach the role to EC2 with an instance profile.',
  },
  {
    sourceType: 'scriptAsset',
    targetType: 's3',
    valid: true,
    severity: 'info',
    message: 'Runtime scripts can be packaged and uploaded to S3 for EC2 bootstrap to download.',
    cdkHint: 'Use s3deploy.BucketDeployment or an asset upload step for the script.',
  },
  {
    sourceType: 'eventBridge',
    targetType: 'lambda',
    valid: true,
    severity: 'info',
    message: 'EventBridge can invoke Lambda by adding the function as a rule target.',
    cdkHint: 'rule.addTarget(new targets.LambdaFunction(lambdaFn))',
  },
  {
    sourceType: 'eventBridge',
    targetType: 'sqs',
    valid: true,
    severity: 'info',
    message: 'EventBridge can route matching events to SQS.',
    cdkHint: 'rule.addTarget(new targets.SqsQueue(queue))',
  },
];

export function findRule(sourceType: string, targetType: string) {
  return awsRules.find((rule) => rule.sourceType === sourceType && rule.targetType === targetType);
}
